global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 5s

scrape_configs:
- job_name: "pushgateway"
  honor_labels: true
  static_configs:
  - targets: [ "emqx-ecp-pushgateway:9091" ]
    labels:
      instance: pushgateway
